[build-system]
requires = ["setuptools>=45", "wheel", "numpy>=2"]
build-backend = "setuptools.build_meta"

[project]
name = "vcztools"
version = "0.0.1"
dependencies = [
    "numpy>=1.23.5",
]
requires-python = ">=3.9"

[project.scripts]
vcztools = "vcztools.__main__:main"

[tool.setuptools]
packages = ["vcztools"]

[tool.pytest.ini_options]
testpaths = ["tests"]
