[build-system]
requires = ["setuptools>=45", "wheel", "numpy>=2"]
build-backend = "setuptools.build_meta"

[project]
name = "vcztools"
version = "0.0.1"
dependencies = [
  "numpy>=1.23.5,<2",
  "numba",
  "zarr>=2.17,<3",
  "click",
]
requires-python = ">=3.9"

[project.scripts]
vcztools = "vcztools.cli:vcztools_main"

[project.optional-dependencies]
dev = [
  "bio2zarr @ git+https://github.com/sgkit-dev/bio2zarr.git",
  "pytest",
  "pytest-datadir",
]

[tool.setuptools]
packages = ["vcztools"]

[tool.pytest.ini_options]
testpaths = ["tests"]
